name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: c
      id: c
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: c
        setup-command: ''
        command: python3 ./CheckLab2.py -f -v
        timeout: 10
        max-score: 1
    - name: 'Grep command '
      id: grep-command
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: 'Grep command '
        setup-command: ''
        command: grep "@myseneca.ca" laboutput.txt
        timeout: 10
        max-score: 2
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        C_RESULTS: "${{steps.c.outputs.result}}"
        GREP-COMMAND_RESULTS: "${{steps.grep-command.outputs.result}}"
      with:
        runners: c,grep-command
